bugs fixed
denis-ttk-1975/algososh pull request #1
Opened 2022-12-06 18:33 UTC by denis-ttk-1975

2022-12-06 19:33 UTC, andryxxa93 requested changes
Отличная работа! Всё работает как надо, вы отлично потрудились. Есть одна единственная проблема - структуры данных Stack и Queue нужно было так же реализовать через класс, как вы это сделали с LinkedList. Сделайте это и ваша работа будет принята.

Удачи!

2022-12-07 15:04 UTC, andryxxa93 requested changes
Всё отлично, единственное что - стали странно работать кнопки "Удалить" и "Очистить" в стеке.

https://user-images.githubusercontent.com/60173362/206214371-ecd20538-21c7-4fc1-8a02-6fa0e753af4f.mov

2022-12-07 15:36 UTC, denis-ttk-1975 commented
> Всё отлично, единственное что - стали странно работать кнопки "Удалить" и "Очистить" в стеке.
> 
>  2022-12-07.18.01.41.mov

Вроде пофиксил. А какой программой вы видео захватываете на экране чтоб его приложить сюда?

2022-12-07 16:44 UTC, andryxxa93 commented
На macbook это родная программа - command+shift+5. Для windows могу порекомендовать iSpring - она бесплатная.

2022-12-07 16:45 UTC, andryxxa93 approved these changes
Отлично! Все замечания учтены, вы отлично поработали. Ваша работа принята.
Желаю удачного продолжения обучения!

2022-12-08 11:39 UTC, merged